version: '3'
services:
  #Servivo de Mongo para la base de datos
  mongodb:
    image: mongo
    container_name: mongo_container
    volumes:
      - "./mongo/import.sh:/docker-entrypoint-initdb.d/import.sh"
      - ./mongo/dump/first_proyect_prod:/dump
    restart: always
    networks:
      - practica_net
  #Servivio de backend
  backend:
    build: ./backend
    container_name: backend_container
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    networks:
      - practica_net
    command: npm run dev
    restart: always
  #Servivio de frontend
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - 4200:4200
    command: npm run start
    restart: always
    depends_on:
      - backend
    networks:
      - practica_net
  #Servio de Mongo con express para monitorizar y administrar la base de datos con una iterface
  mongo-express:
    image: mongo-express
    container_name: adminMongo_container
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_container
    ports:
      - "8081:8081"
    restart: always
    networks:
      - practica_net
  #Servicio de Loadbalancer para repartir o administrar la carga 
  loadbalancer_nginx:
    image: nginx
    container_name: loadbalancer
    volumes:
      - "./loadbalancer/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - practica_net
    ports:
      - "8082:80"
    restart: always
    command: nginx -g 'daemon off;'
  #Servicio de Prometheus para monitorizar las metricas
  prometheus:
    image: prom/prometheus:v2.20.1
    ports:
      - "9090:9090"
    container_name: prometheus_practica
    volumes:
    - "./prometheus/:/etc/prometheus"
    networks:
      - practica_net
    command: --config.file=/etc/prometheus/prometheus.yml
  #Servicio de Grafana, nos permite la visualización y el formato de datos métricos del Prometheus
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana_practica
    restart: always
    ports:
      - "3500:3000"
    volumes:
      - ./prometheus/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - myGrafanaVol:/var/lib/grafana
    env_file:
      - ./prometheus/.env
    depends_on:
      - prometheus
    networks:
      - practica_net
#Red que utilizara todos los servicios para poder comunicarse entre ellos
networks:
  practica_net:
#Declaración de volumenes
volumes:
  myGrafanaVol:
