version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo_container
    volumes:
      - "./mongo/import.sh:/docker-entrypoint-initdb.d/import.sh"
      - ./mongo/dump/first_proyect_prod:/dump
    restart: always
    networks:
      - wishpop
  backend:
    build: ./backend
    container_name: backend_container
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    networks:
      - wishpop
    command: npm run dev
    restart: always
  frontend:
    build: ./frontend
networks:
  wishpop:
