version: '3'
services:
  #crearemos un servicio que utilizaremos para realizar la conexión a la base de datos
  mongodb:
    image: mongo
    container_name: mongo_container
    volumes:
      - "./mongo/import.sh:/docker-entrypoint-initdb.d/import.sh"
      - ./mongo/dump/first_proyect_prod:/dump
    restart: always
    networks:
      - practica_net
  backend:
    build: ./backend
    container_name: backend_container
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    networks:
      - practica_net
    command: npm run dev
    restart: always
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - 4200:4200
    command: npm run start
    restart: always
    depends_on:
      - backend
    networks:
      - practica_net
  mongo-express:
    image: mongo-express
    container_name: adminMongo_container
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_container
    ports:
      - "8081:8081"
    restart: always
    networks:
      - practica_net
  loadbalancer_nginx:
    image: nginx
    container_name: loadbalancer
    volumes:
      - "./loadbalancer/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - practica_net
    ports:
      - "8082:80"
    restart: always
    command: nginx -g 'daemon off;'
  prometheus:
    image: prom/prometheus:v2.20.1
    ports:
      - "9090:9090"
    container_name: prometheus_practica
    volumes:
    - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - practica_net
    command: --config.file=/etc/prometheus/prometheus.yml
# Necesitaremos declarar una network para que los diferentes servicos se puedean comunicar entre ellos
networks:
  practica_net:
