version: '3'
services:
  #crearemos un servicio que utilizaremos para realizar la conexión a la base de datos
  mongodb:
    image: mongo
    container_name: mongo_container
    volumes:
      - "./mongo/import.sh:/docker-entrypoint-initdb.d/import.sh"
      - ./mongo/dump/first_proyect_prod:/dump
    restart: always
    networks:
      - practica_net
  backend:
    build: ./backend
    container_name: backend_container
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    networks:
      - practica_net
    command: npm run dev
    restart: always
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - 4200:4200
    command: npm run start
    restart: always
    depends_on:
      - backend
    networks:
      - practica_net
# Necesitaremos declarar una network para que los diferentes servicos se puedean comunicar entre ellos
networks:
  practica_net:
