# STAGE 1 --> encargado de instalar todas las dependencias necesarias.
FROM node:19-alpine AS install
WORKDIR /app
COPY package.json .
RUN npm install

# STAGE 2 --> copiaremos todas las dependencias necesarias del Stage 1 y los archivos y variables de entorno que necesitaremos del proyecto.
FROM node:19-alpine
WORKDIR /app
COPY --from=install /app/node_modules ./node_modules
COPY package.json .
COPY package-lock.json .
COPY app ./app
COPY server.js .
COPY ./env_example.txt ./.env
RUN apk update && apk add bash
EXPOSE 3000